---
abstract: "It's new $module"
author:
  - 'Toshinori Sato (@overlast) <overlasting@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-SetSimilarity
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/overlast/p5-Algorithm-SetSimilarity/issues
  homepage: https://github.com/overlast/p5-Algorithm-SetSimilarity
  repository: git://github.com/overlast/p5-Algorithm-SetSimilarity.git
version: 0.0.0_01
